# Generated by Django 6.0.5 on 2026-06-19 16:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mac', models.CharField(help_text='MAC normalizada: sin separadores, uppercase. Ej: AABBCCDDEEFF', max_length=12, verbose_name='MAC del servidor')),
                ('nit', models.CharField(help_text='NIT normalizado uppercase. Ej: 900123456-7', max_length=20, verbose_name='NIT')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('trial_used', models.BooleanField(default=False, help_text='Solo SuperAdmin puede resetear. Se registra en AuditLog.', verbose_name='Prueba usada')),
                ('anomalies_count', models.PositiveIntegerField(default=0, help_text='Rollbacks de reloj y tokens manipulados reportados.', verbose_name='Anomalías detectadas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mac', 'nit'], name='licenses_cl_mac_c79019_idx'), models.Index(fields=['nit'], name='licenses_cl_nit_74b741_idx')],
                'unique_together': {('mac', 'nit')},
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_type', models.CharField(choices=[('commercial', 'Comercial'), ('trial', 'Prueba gratuita')], default='commercial', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('expired', 'Vencida'), ('revoked', 'Revocada'), ('pending', 'Pendiente')], default='active', max_length=20, verbose_name='Estado')),
                ('expiry_date', models.DateTimeField(verbose_name='Vence el')),
                ('activated_at', models.DateTimeField(auto_now_add=True, verbose_name='Activada')),
                ('last_validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Última validación online')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revocada el')),
                ('notes', models.TextField(blank=True, help_text='Observaciones del administrador.', verbose_name='Notas')),
                ('activated_by', models.ForeignKey(blank=True, help_text='Solo se llena si la activación fue manual desde el panel.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_licenses', to=settings.AUTH_USER_MODEL, verbose_name='Activada por (admin)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='licenses.client', verbose_name='Cliente')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_licenses', to=settings.AUTH_USER_MODEL, verbose_name='Revocada por')),
            ],
            options={
                'verbose_name': 'Licencia',
                'verbose_name_plural': 'Licencias',
                'ordering': ['-activated_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ACTIVATE', 'Activación'), ('VALIDATE', 'Validación'), ('TRIAL_ACTIVATE', 'Prueba activada'), ('REVOKE', 'Revocación'), ('ANOMALY', 'Anomalía detectada'), ('MANUAL_ACTIVATE', 'Activación manual'), ('TRIAL_RESET', 'Reset de prueba')], max_length=30, verbose_name='Acción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('result', models.CharField(choices=[('success', 'Éxito'), ('rejected', 'Rechazado'), ('error', 'Error')], default='success', max_length=20, verbose_name='Resultado')),
                ('detail', models.JSONField(blank=True, default=dict, help_text='Datos adicionales del evento en formato JSON.', verbose_name='Detalle')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario admin')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='licenses.client', verbose_name='Cliente')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='licenses.license', verbose_name='Licencia')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['status'], name='licenses_li_status_40a808_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['expiry_date'], name='licenses_li_expiry__ba1ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['client', 'status'], name='licenses_li_client__2a8d89_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='licenses_au_action_eac781_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='licenses_au_created_3c6ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['client', 'created_at'], name='licenses_au_client__a8536f_idx'),
        ),
    ]
